CREATE TABLE all_data_types(
   col_bigint bigint NULL,
   col_int int NULL,
   col_smallint smallint NULL,
   col_tinyint tinyint NULL,
   col_bit bit NULL,
   col_decimal decimal(10, 2) NULL,
   col_numeric numeric(10, 2) NULL,
   col_money money NULL,
   col_smallmoney smallmoney NULL,
   col_float real NULL,
   col_real real NULL,
   col_date date NULL,
   col_time time(0) NULL,
   col_datetime datetime NULL,
   col_datetime2 datetime2(0) NULL,
   col_smalldatetime smalldatetime NULL,
   col_char char(10) NULL,
   col_varchar varchar(50) NULL,
   col_text text NULL,
   col_nchar nchar(10) NULL,
   col_nvarchar nvarchar(50) NULL,
   col_ntext ntext NULL,
   col_binary binary(10) NULL,
   col_varbinary varbinary(50) NULL
);
